import { SignInButton, SignOutButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.post.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && (
          <>
            {data?.map((post) => (
              <div key={post.id}>{post.content}</div>
            ))}
            <SignOutButton />
          </>
        )}
      </main>
    </>
  );
};

export default Home;
